name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install the CloudFoundry CLI
        run: |
          wget https://s3-us-west-1.amazonaws.com/v7-cf-cli-releases/releases/v7.2.0/cf7-cli-installer_7.2.0_x86-64.deb
          sudo dpkg -i cf7-cli-installer_7.2.0_x86-64.deb

      - uses: actions/checkout@master
      - name: Build site
        run: |
          gem install bundler
          bundle install
          bundle exec middleman build

      - name: Deploy site to staging
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        run: |
          cf api https://api.london.cloud.service.gov.uk
          cf auth
          cf target -o national-lottery-heritage-fund
          cf target -s sandbox
          cf push dsdt-tech-docs -f manifest.yml --strategy rolling
